config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.user.urls')),
    path('report/', include('core.report.urls')),
    path('messaging/', include('core.messaging.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/messaging/urls.py
from django.urls import path
from .views import send_message, inbox, message_detail

app_name = 'messaging'

urlpatterns = [
    path('send_message/<int:user_id>/', send_message, name='send_message'),
    path('message/<int:sender_id>/', message_detail, name='message_detail'),  # Cambiado a sender_id
    path('inbox/', inbox, name='inbox'),
]

core/messaging/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_messages', on_delete=models.CASCADE)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"From {self.sender} to {self.recipient} - {self.timestamp}"

    class Meta:
        ordering = ['-timestamp']

core/messaging/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']


class MessageReplyForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Escribe tu mensaje aquí...'}),
        }

core/messaging/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from core.user.models import User
from .models import Message
from .forms import MessageForm, MessageReplyForm
from django.db.models import Q

@login_required
def send_message(request, user_id):
    recipient = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.recipient = recipient
            message.save()
            return redirect('user:dashboard')
    else:
        form = MessageForm(initial={'recipient': recipient})
    return render(request, 'send_message.html', {'form': form, 'recipient': recipient})

@login_required
def message_detail(request, sender_id):
    user = request.user
    sender = get_object_or_404(User, id=sender_id)
    messages = Message.objects.filter(
        (Q(sender=sender) & Q(recipient=user)) | (Q(sender=user) & Q(recipient=sender))
    ).order_by('timestamp')

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.sender = user
            reply.recipient = sender
            reply.save()
            return redirect('messaging:message_detail', sender_id=sender.id)
    else:
        form = MessageForm()

    return render(request, 'message_detail.html', {'sender': sender, 'messages': messages, 'form': form})

@login_required
def inbox(request):
    # Obtener todos los mensajes recibidos por el usuario
    messages = Message.objects.filter(recipient=request.user).order_by('-timestamp')
    
    # Contar mensajes no leídos
    unread_message_count = messages.filter(read=False).count()
    
    # Diccionario para almacenar el último mensaje por cada remitente
    unique_messages = {}
    
    for message in messages:
        # Usar el ID del remitente como clave para el diccionario
        sender_id = message.sender.id
        if sender_id not in unique_messages:
            unique_messages[sender_id] = message
    
    # Convertir el diccionario de mensajes únicos de nuevo a una lista
    unique_message_list = list(unique_messages.values())

    context = {
        'messages': unique_message_list,
        'unread_message_count': unread_message_count,
    }

    return render(request, 'inbox.html', context)

core/messaging/templates/inbox.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-8">
    <h2 class="text-2xl font-bold mb-4">Bandeja de Entrada</h2>
    <ul>
        {% for message in messages %}
        <li class="mb-4 p-4 border rounded-md {% if not message.read %}bg-gray-100{% endif %}">
            <a href="{% url 'messaging:message_detail' message.sender.id %}" class="flex items-center">
                {% if message.sender.profile_image %}
                    <img src="{{ message.sender.profile_image.url }}" alt="Imagen de Perfil" class="rounded-full h-10 w-10 mr-4">
                {% else %}
                    <img src="{% static 'img/default_profile.jpg' %}" alt="Imagen de Perfil por defecto" class="rounded-full h-10 w-10 mr-4">
                {% endif %}
                <div>
                    <strong>{{ message.sender.username }}</strong><br>
                    <span>{{ message.content|truncatechars:50 }}</span><br>
                    <span class="text-sm text-gray-600">{{ message.timestamp|date:"Y-m-d H:i" }}</span>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

core/messaging/templates/message_detail.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-8">
    <h2 class="text-2xl font-bold mb-4">Conversación con {{ sender.username }}</h2>
    <div class="flex flex-col"> <!-- Contenedor principal en columna -->
        {% for msg in messages %}
        <div class="w-full mb-4 {% if msg.sender == request.user %}text-right{% endif %}"> <!-- Contenedor de mensajes -->
            <div class="mb-4 p-4 border rounded-md bg-gray-100 inline-block max-w-3/4 {% if msg.sender == request.user %}ml-auto{% endif %}"> <!-- Contenedor de mensaje -->
                <div class="flex items-start {% if msg.sender == request.user %}justify-end{% endif %}"> <!-- Contenido del mensaje -->
                    {% if msg.sender.profile_image %}
                        <img src="{{ msg.sender.profile_image.url }}" alt="Imagen de Perfil" class="rounded-full h-10 w-10 {% if msg.sender == request.user %}ml-4{% else %}mr-4{% endif %}">
                    {% else %}
                        <img src="{% static 'img/default_profile.jpg' %}" alt="Imagen de Perfil por defecto" class="rounded-full h-10 w-10 {% if msg.sender == request.user %}ml-4{% else %}mr-4{% endif %}">
                    {% endif %}
                    <div>
                        <strong>{{ msg.sender.username }}</strong><br>
                        <span>{{ msg.content }}</span><br>
                        <span class="text-sm text-gray-600">{{ msg.timestamp|date:"Y-m-d H:i" }}</span>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <h3 class="text-xl font-bold mb-4">Responder</h3>
    <form method="post" class="max-w-screen-xl mx-auto px-4">
        {% csrf_token %}
        <div class="flex flex-wrap -mx-4 mb-6">
            <div class="w-full px-4 mb-6">
                <textarea name="{{ form.content.name }}" rows="5" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="{{ form.content.field.widget.attrs.placeholder }}"></textarea>
                {% if form.content.errors %}
                    <p class="text-red-500 text-xs italic">{{ form.content.errors }}</p>
                {% endif %}
            </div>
        </div>
        <div class="flex items-center justify-end">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded-md shadow-sm">Enviar</button>
        </div>
    </form>
</div>
{% endblock %}

core/messaging/templates/send_message.html
{% extends "sidebar.html" %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h2 class="text-2xl font-bold mb-4">Enviar Mensaje a {{ recipient.username }}</h2>
    <form method="post" class="max-w-md mx-auto">
        {% csrf_token %}
        <div class="mb-4">
            <label for="id_content" class="block text-sm font-medium text-gray-700">Mensaje</label>
            <textarea id="id_content" name="content" rows="5" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="Escribe tu mensaje aquí..."></textarea>
            {% if form.content.errors %}
                <p class="text-red-500 text-xs italic">{{ form.content.errors }}</p>
            {% endif %}
        </div>
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded-md shadow-sm mt-2">Enviar</button>
    </form>
</div>
{% endblock %}