config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.user.urls')),
    path('report/', include('core.report.urls')),
    path('messaging/', include('core.messaging.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/report/urls.py
from django.urls import path
from .views import create_report, success_view, edit_report, delete_report, report_list, like_report, add_comment, map_view

app_name = 'report'

urlpatterns = [
    path('', create_report, name='create_report'),
    path('report_list', report_list, name='report_list'),
    path('success/', success_view, name='success'),
    path('edit/<int:report_id>/', edit_report, name='edit_report'),
    path('delete/<int:report_id>/', delete_report, name='delete_report'),
    path('like/<int:report_id>/', like_report, name='like_report'),
    path('comment/<int:report_id>/', add_comment, name='add_comment'),
    path('map/', map_view, name='map'),
]

core/report/models.py
from django.db import models
from django.conf import settings

class Report(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pet_description = models.TextField()
    post_description = models.TextField()
    media = models.ImageField(upload_to='reports/', null=True, blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='report_likes', blank=True)
    latitude = models.DecimalField(max_digits=12, decimal_places=9, null=True, blank=True)  # Campo para latitud
    longitude = models.DecimalField(max_digits=12, decimal_places=9, null=True, blank=True)  # Campo para longitud

    def __str__(self):
        return f"Report by {self.user.username}"

    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.report}"

core/report/forms.py
from django import forms
from .models import Report, Comment

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['pet_description', 'post_description', 'media', 'latitude', 'longitude']
        widgets = {
            'pet_description': forms.Textarea(attrs={'rows': 3, 'class': 'w-full border rounded-md p-2'}),
            'post_description': forms.Textarea(attrs={'rows': 3, 'class': 'w-full border rounded-md p-2'}),
            'media': forms.ClearableFileInput(attrs={'class': 'block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100'}),
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
        }

class ReportDeleteForm(forms.Form):
    confirm_delete = forms.BooleanField(label='Confirmar eliminación', required=True)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 2, 'class': 'w-full border rounded-md p-2'}),
        }

core/report/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ReportForm, ReportDeleteForm, CommentForm
from .models import Report

@login_required
def create_report(request):
    if request.method == 'POST':
        form = ReportForm(request.POST, request.FILES)
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user
            report.save()
            return redirect('report:success')
    else:
        form = ReportForm()
    return render(request, 'report.html', {'form': form})

@login_required
def success_view(request):
    return render(request, 'success.html')

@login_required
def report_list(request):
    reports = Report.objects.filter(user=request.user)
    comment_form = CommentForm()
    return render(request, 'report_list.html', {'reports': reports, 'comment_form': comment_form})

@login_required
def edit_report(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    if request.method == 'POST':
        form = ReportForm(request.POST, request.FILES, instance=report)
        if form.is_valid():
            form.save()
            return redirect('report:report_list')
    else:
        form = ReportForm(instance=report)
    
    return render(request, 'edit_report.html', {'form': form})

@login_required
def delete_report(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    if request.method == 'POST':
        report.delete()
        return redirect('report:report_list')
    
    form = ReportDeleteForm()
    
    return render(request, 'delete_report.html', {'report': report, 'form': form})


@login_required
def like_report(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    if report.likes.filter(id=request.user.id).exists():
        report.likes.remove(request.user)
    else:
        report.likes.add(request.user)
    return redirect('user:dashboard')

@login_required
def add_comment(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.report = report
            comment.save()
    return redirect('user:dashboard')


@login_required
def map_view(request):
    reports = Report.objects.exclude(latitude__isnull=True, longitude__isnull=True)  # Filtrar reportes con coordenadas
    report_list = [
        {
            'user': report.user.username,
            'pet_description': report.pet_description,
            'post_description': report.post_description,
            'latitude': float(report.latitude),
            'longitude': float(report.longitude),
            'media': report.media.url if report.media else ''
        }
        for report in reports
    ]
    return render(request, 'maps.html', {'reports': report_list})

core/report/templates/delete_report.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-8">
    <h2 class="text-2xl font-bold mb-4">Eliminar Reporte</h2>
    <div class="bg-white rounded-lg shadow-md p-8 max-w-lg mx-auto">
        <p class="text-gray-800 mb-4">¿Estás seguro de que quieres eliminar este reporte?</p>
        <div class="mb-4">
            <p class="font-bold">Descripción de la Mascota:</p>
            <p class="text-gray-700">{{ report.pet_description }}</p>
        </div>
        <div class="mb-4">
            <p class="font-bold">Imagen:</p>
            {% if report.media %}
            <img src="{{ report.media.url }}" alt="Imagen del Reporte" class="rounded-lg shadow-md h-60 w-60">
            {% else %}
            <p>No hay imagen disponible.</p>
            {% endif %}
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="flex justify-between">
                <button type="submit" class="bg-red-500 hover:bg-red-700 text-white py-2 px-4 rounded-md shadow-sm">Eliminar Reporte</button>
                <a href="{% url 'report:report_list' %}" class="bg-gray-300 hover:bg-gray-400 text-gray-800 py-2 px-4 rounded-md shadow-sm">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

core/report/templates/edit_report.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<div class="container mx-auto px-4 py-8">
    <h2 class="text-2xl font-bold mb-4">Editar Reporte</h2>
    <div class="flex justify-center">
        <div class="max-w-lg bg-white rounded-lg shadow-md p-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="grid grid-cols-1 gap-4">
                    <div class="mb-4">
                        <label for="id_pet_description" class="block text-gray-700 font-bold mb-2">Descripción de la Mascota:</label>
                        {{ form.pet_description }}
                    </div>
                    <div class="mb-4">
                        <label for="id_pet_description" class="block text-gray-700 font-bold mb-2">Descripción de la Mascota:</label>
                        {{ form.post_description }}
                    </div>
                    <div class="mb-4">
                        <label for="id_media" class="block text-gray-700 font-bold mb-2">Imagen:</label>
                        {% if form.instance.media %}
                            <img src="{{ form.instance.media.url }}" alt="Imagen de reporte" class="rounded-lg shadow-md mb-4 h-60 w-60 mx-auto block">
                        {% endif %}
                        {{ form.media }}
                    </div>
                </div>
                <div class="flex justify-between">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded-md shadow-sm">Guardar cambios</button>
                    <a href="{% url 'report:report_list' %}" class="bg-gray-300 hover:bg-gray-400 text-gray-800 py-2 px-4 rounded-md shadow-sm">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

core/report/templates/maps.html
{% extends "sidebar.html" %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h2 class="text-2xl font-bold mb-4 text-white">Localiza a tu mascota</h2>
    <div id="map" class="h-96 w-full"></div>
</div>

<script>
    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 10,
            center: {lat: 0, lng: 0} // Centrar el mapa en coordenadas específicas o ajustar automáticamente
        });

        var reports = {{ reports|safe }}; // Obtener los reportes perdidos desde Django, asegúrate de que se pase correctamente

        reports.forEach(function(report) {
            var marker = new google.maps.Marker({
                position: {lat: parseFloat(report.latitude), lng: parseFloat(report.longitude)},
                map: map,
                title: report.user // Mostrar el nombre de usuario del propietario del reporte
            });

            var infowindow = new google.maps.InfoWindow({
                content: `
                    <div>
                        <h3>${report.user}</h3>
                        <p>${report.pet_description}</p>
                        <p>${report.post_description}</p>
                        <img src="${report.media}" alt="Imagen de Mascota" style="max-width: 200px;">
                    </div>
                `
            });

            marker.addListener('click', function() {
                infowindow.open(map, marker);
            });
        });

        // Ajustar el mapa para mostrar todos los marcadores
        if (reports.length > 0) {
            var bounds = new google.maps.LatLngBounds();
            reports.forEach(function(report) {
                bounds.extend(new google.maps.LatLng(report.latitude, report.longitude));
            });
            map.fitBounds(bounds);
        }
    }

    // Inicializar el mapa cuando la página cargue
    window.onload = function() {
        initMap();
    };
</script>

<!-- Incluir el script de la API de Google Maps -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYTIrdYoQgrpBfZayR30G6_ObZViJ1Tn4&callback=initMap" async defer></script>
{% endblock %}

core/report/templates/report.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<div class="flex items-center justify-center min-h-screen">
    <div class="bg-white rounded-lg shadow-md p-8 max-w-lg w-full">
        <h1 class="text-2xl font-bold mb-4">Reporte</h1>
        <p class="text-gray-700 mb-6">Crea tu reporte de mascota perdida para empezar la difusión 😢<br>Por favor, comparte los datos necesarios para ayudarte a verificar dónde está tu mascota.</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-4">
                <label class="block text-gray-700">1. Descripción de la mascota:</label>
                <textarea name="pet_description" class="w-full border rounded-md p-2" rows="3"></textarea>
            </div>
            <div class="mb-4">
                <label class="block text-gray-700">2. Descripción de la publicación:</label>
                <textarea name="post_description" class="w-full border rounded-md p-2" rows="3"></textarea>
            </div>
            <div class="mb-4">
                <label class="block text-gray-700">3. Comparte una foto o video de tu mascota:</label>
                <input type="file" name="media" class="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" />
            </div>
            <div class="mb-4">
                <label class="block text-gray-700">4. Ubicación donde se perdió:</label>
                <input type="text" id="location" class="w-full border rounded-md p-2" placeholder="Ingresa la ubicación">
            </div>
            <input type="hidden" name="latitude" id="latitude">
            <input type="hidden" name="longitude" id="longitude">
            <div class="text-center">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-blue-700">Enviar</button>
            </div>
        </form>
    </div>
</div>

<!-- Cargar la API de Google Maps de forma asíncrona -->
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYTIrdYoQgrpBfZayR30G6_ObZViJ1Tn4&libraries=places&callback=initAutocomplete"
    async
    defer
></script>
<script>
    let autocomplete;
    function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(
            document.getElementById('location'),
            { types: ['geocode'] }
        );

        autocomplete.addListener('place_changed', function() {
            const place = autocomplete.getPlace();
            document.getElementById('latitude').value = place.geometry.location.lat();
            document.getElementById('longitude').value = place.geometry.location.lng();
        });
    }
</script>
{% endblock content %}

core/report/templates/report_list.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<body class="bg-gray-100 flex">
    <div class="flex-1 p-10">
        <section class="text-center py-10 bg-white rounded-lg shadow-md">
            <div class="container mx-auto px-4">
                <h2 class="text-2xl lg:text-3xl text-gray-800 font-bold mb-4">Mis Reportes</h2>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {% if reports %}
                        {% for report in reports %}
                        <div class="bg-white rounded-lg shadow-md p-6 relative">
                            <div class="flex items-center justify-between mb-4">
                                <div class="flex items-center">
                                    {% if report.user.profile_image %}
                                        <img src="{{ report.user.profile_image.url }}" alt="Imagen de perfil de {{ report.user.username }}" class="rounded-full h-10 w-10 mr-3">
                                    {% else %}
                                        <img src="{% static 'img/default_profile.jpg' %}" alt="Imagen de perfil por defecto" class="rounded-full h-10 w-10 mr-3">
                                    {% endif %}
                                    <span class="text-gray-800 font-bold">{{ report.user.username }}</span>
                                </div>
                                <div class="relative">
                                    <button id="dropdownBtn{{ report.id }}" class="text-gray-600 focus:outline-none" onclick="toggleDropdown('{{ report.id }}')">
                                        <i class="bx bx-dots-vertical-rounded text-3xl"></i>
                                    </button>
                                    <div id="dropdownMenu{{ report.id }}" class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg z-10 hidden">
                                        <a href="{% url 'report:edit_report' report.id %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Editar</a>
                                        <a href="{% url 'report:delete_report' report.id %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Eliminar</a>
                                    </div>
                                </div>
                            </div>
                            {% if report.media %}
                            <div class="flex justify-center items-center">
                                <img src="{{ report.media.url }}" alt="Report Image" class="rounded-lg shadow-md mb-4 h-60 w-60">
                            </div>
                            {% endif %}
                            <p class="text-gray-800 mb-4">{{ report.pet_description }}</p>
                            <p class="text-gray-800 mb-4">{{ report.post_description }}</p>
                            <div class="flex items-center">
                                <i class='bx bx-heart text-2xl text-gray-700 mr-2'></i> <span>1,489</span>
                                <i class='bx bx-comment text-2xl text-gray-700 ml-6 mr-2'></i> <span>3,000</span>
                            </div>
                        </div>
                        {% endfor %}
                    {% else %}
                        <p class="text-gray-800">No tienes reportes creados.</p>
                    {% endif %}
                </div>
            </div>
        </section>
    </div>
</body>
<script>
    // Función para alternar la visibilidad del menú desplegable
    function toggleDropdown(reportId) {
        const dropdownMenu = document.getElementById(`dropdownMenu${reportId}`);
        dropdownMenu.classList.toggle('hidden');
    }

    // Cerrar el menú desplegable al hacer clic fuera de él
    document.addEventListener('click', function(event) {
        if (!event.target.matches('.bx-dots-vertical-rounded')) {
            const dropdowns = document.getElementsByClassName('rounded-md shadow-lg');
            for (let i = 0; i < dropdowns.length; i++) {
                const dropdownMenu = dropdowns[i];
                if (!dropdownMenu.classList.contains('hidden')) {
                    dropdownMenu.classList.add('hidden');
                }
            }
        }
    });
</script>
{% endblock content %}

core/report/templates/success.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<div class="flex items-center justify-center min-h-screen">
    <div class="bg-white rounded-lg shadow-md p-8 max-w-lg w-full text-center">
        <h1 class="text-2xl font-bold mb-4">Reporte Enviado</h1>
        <p class="text-gray-700 mb-6">¡Gracias por enviar tu reporte! Haremos nuestro mejor esfuerzo para ayudarte a encontrar a tu mascota.</p>
        <a href="{% url 'report:create_report' %}" class="bg-blue-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-blue-700">Crear otro reporte</a>
    </div>
</div>
{% endblock content %}