config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.user.urls')),
    path('report/', include('core.report.urls')),
    path('messaging/', include('core.messaging.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/messaging/urls.py
from django.urls import path
from .views import send_message, inbox, message_detail

app_name = 'messaging'

urlpatterns = [
    path('send_message/<int:user_id>/', send_message, name='send_message'),
    path('message/<int:sender_id>/', message_detail, name='message_detail'),  # Cambiado a sender_id
    path('inbox/', inbox, name='inbox'),
]

core/report/urls.py
from django.urls import path
from .views import create_report, success_view, edit_report, delete_report, report_list, like_report, add_comment, map_view

app_name = 'report'

urlpatterns = [
    path('', create_report, name='create_report'),
    path('report_list', report_list, name='report_list'),
    path('success/', success_view, name='success'),
    path('edit/<int:report_id>/', edit_report, name='edit_report'),
    path('delete/<int:report_id>/', delete_report, name='delete_report'),
    path('like/<int:report_id>/', like_report, name='like_report'),
    path('comment/<int:report_id>/', add_comment, name='add_comment'),
    path('map/', map_view, name='map'),
]

core/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile_view, name='profile'),
]

templates/home.html
{% load static %}
{% load crispy_forms_tags %} 
{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Guardian</title>

    <!-- Enlaces a estilos -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.1/dist/tailwind.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>

</head>
<body class="bg-gradient-to-b from-blue-500 to-green-500">
  <nav class="bg-blue-500 py-4">
    <div class="container mx-auto px-4 flex items-center justify-between">
      <a href="" class="text-white text-xl font-bold">
        <img src="{% static 'img/logo.svg' %}" alt="Logo" class="h-8" />
      </a>
      <ul class="hidden lg:flex gap-4 text-white font-bold">
        <li><a href="#" class="hover:text-gray-300">Donaciones</a></li>
        <li><a href="#" class="hover:text-gray-300">Testimonios</a></li>
        <li><a href="#" class="hover:text-gray-300">Contáctanos</a></li>
        <li><a href="#" class="hover:text-gray-300">Sobre nosotros</a></li>
      </ul>
      <button
        class="lg:hidden text-white focus:outline-none"
        type="button"
        aria-label="Toggle navigation"
      >
        <i class="bx bx-menu text-3xl"></i>
      </button>
    </div>
  </nav>

  <header class="bg-gradient-to-b from-blue-500 to-green-500 text-center py-20">
    <h1 class="text-4xl lg:text-5xl text-white font-bold mb-4">Pet Guardian</h1>
    <p class="text-lg lg:text-xl text-white mb-8">Encuentra a tu mascota</p>
    <div class="max-w-xl mx-auto mb-8">
      <img
        src="{% static 'img/lostpet.png' %}"
        alt="Lost Pet"
        class="rounded-lg shadow-md"
      />
    </div>
    <h2 class="text-2xl lg:text-3xl text-white font-bold mb-4">
      ¿Has perdido a tu querida mascota?
    </h2>
    <p class="text-lg lg:text-xl text-white mb-8">
      Sabemos lo angustiante que puede ser esa situación. Pero no te preocupes,
      estamos aquí para ayudarte a reunirte con tu peludo amigo lo antes
      posible.
    </p>
    <a
      href="{% url 'user:register' %}"
      class="bg-green-500 mb-12 hover:bg-green-600 text-white font-bold py-3 px-6 rounded-lg text-xl"
      >REGÍSTRATE AHORA</a
    >
    <a
      href="{% url 'user:login' %}"
      class="bg-green-500 mb-12 hover:bg-green-600 text-white font-bold py-3 px-6 rounded-lg text-xl"
      >INICIA SESION</a
    >
  </header>

  <section class="bg-gradient-to-b from-green-500 text-center py-10 bg-white">
    <div class="container mx-auto px-4">
      <p class="text-lg lg:text-xl text-white mb-8">
        Nuestra plataforma está diseñada para conectarte con personas que pueden
        haber visto a tu mascota perdida. Simplemente reporta la pérdida de tu
        mascota y deja que nuestra red de usuarios te ayude en la búsqueda.
      </p>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        <img
          src="{% static 'img/photo1.png' %}"
          alt="Pet 1"
          class="rounded-lg shadow-md"
        />
        <img
          src="{% static 'img/photo2.png' %}"
          alt="Pet 2"
          class="rounded-lg shadow-md"
        />
        <img
          src="{% static 'img/photo3.png' %}"
          alt="Pet 3"
          class="rounded-lg shadow-md"
        />
      </div>
    </div>
  </section>
</body>
{% endblock content %}

templates/navbar.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Guardian</title>

    <!-- Enlaces a estilos -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.1/dist/tailwind.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>

</head>
<body class="bg-gradient bg-primary">
    <nav class="bg-blue-500 py-4">
        <div class="container mx-auto px-4 flex items-center justify-between">
            <a href="" class="text-white text-xl font-bold">
                <img src="{% static 'img/logo.svg' %}" alt="Logo" class="h-8">
            </a>
            <button
                class="lg:hidden text-white focus:outline-none"
                type="button"
                aria-label="Toggle navigation"
            >
                <i class="bx bx-menu text-3xl"></i>
            </button>
            <div class="hidden lg:flex lg:flex-grow lg:items-center lg:justify-end" id="navbarSupportedContent">
                {% if user.is_authenticated %}
                    <ul class="flex gap-4 text-white font-bold">
                        <li><a href="#" class="hover:text-gray-300">Inicio</a></li>
                    </ul>
                    <div class="relative ml-4">
                        <button
                            id="user-menu-btn"
                            class="flex items-center text-white font-bold focus:outline-none"
                            aria-label="User menu"
                        >
                            <img
                                src="https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png"
                                alt="Avatar"
                                class="rounded-full h-8 mr-2"
                            />
                            <span>{{ user.username }}</span>
                            <i class="bx bx-chevron-down ml-2"></i>
                        </button>
                        <ul
                            id="user-menu"
                            class="absolute right-0 mt-2 w-48 bg-white border border-gray-200 rounded-md shadow-lg hidden"
                        >
                            <li><a href="" class="block px-4 py-2 text-gray-700 hover:bg-gray-100">Mi perfil</a></li>
                            <li><a href="{% url 'user:logout' %}" class="block px-4 py-2 text-gray-700 hover:bg-gray-100">Cerrar sesión</a></li>
                        </ul>
                    </div>
                {% else %}
                    <div class="flex gap-12">
                        <a href="{% url 'user:home' %}" class="text-white font-bold hover:text-gray-200">INICIO</a>
                        <a href="{% url 'user:register' %}" class="text-white font-bold hover:text-gray-200">REGISTER</a>
                        <a href="{% url 'user:login' %}" class="text-white font-bold hover:text-gray-200">LOGIN</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>


    {% block content %}
    <!-- Contenido específico de la página -->
    {% endblock content %}

    <footer class="bg-green-500 text-white text-center py-4">
        <div class="container mx-auto px-4">
            <div class="flex justify-center gap-4">
                <a href="#" class="text-white text-3xl hover:text-gray-200 transition-colors duration-300"><i class='bx bxl-facebook-circle'></i></a>
                <a href="#" class="text-white text-3xl hover:text-gray-300 transition-colors duration-300"><i class='bx bxl-twitter'></i></a>
                <a href="#" class="text-white text-3xl hover:text-gray-300 transition-colors duration-300"><i class='bx bxl-linkedin'></i></a>
                <a href="#" class="text-white text-3xl hover:text-gray-300 transition-colors duration-300"><i class='bx bxl-instagram'></i></a>
            </div>
        </div>
    </footer>

    <!-- Script para manejar el menú desplegable del usuario -->
     <script src="{% static 'js/usermodal.js' %}"></script>
</body>
</html>

templates/sidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Guardian Dashboard</title>

    <!-- Enlaces a estilos -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.1/dist/tailwind.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
</head>
<body class="bg-gradient-to-b from-blue-400 to-green-400 flex">
    <nav class="bg-blue-500 w-64 h-screen flex flex-col items-center py-4">
        <div class="flex items-center mb-8">
            <img src="{% static 'img/logo.svg' %}" alt="Logo" class="h-8 mr-2">
            <span class="text-white text-xl font-bold">PetGuardian</span>
        </div>
        <ul class="text-white font-bold space-y-4 w-full text-center">
            <li><a href="{% url 'user:dashboard' %}" class="hover:text-gray-300 block py-2">Inicio</a></li>
            <li><a href="{% url 'user:profile' %}" class="hover:text-gray-300 block py-2">Perfil</a></li>
            <li>
                <a href="{% url 'messaging:inbox' %}" class="hover:text-gray-300 block py-2 relative">
                    Messages
                    {% if unread_message_count > 0 %}
                        <span class="bg-red-500 text-white rounded-full px-2 py-1 text-xs absolute top-0 right-0 transform translate-x-1/2 -translate-y-1/2">{{ unread_message_count }}</span>
                    {% endif %}
                </a>
            </li>
            <li><a href="{% url 'report:create_report' %}" class="hover:text-gray-300 block py-2">Reportar</a></li>
            <li><a href="{% url 'report:report_list' %}" class="hover:text-gray-300 block py-2">Mis Reportes</a></li>
            <li><a href="{% url 'report:map' %}" class="hover:text-gray-300 block py-2">Mapa</a></li>
        </ul>
        <a href="{% url 'user:logout' %}" class="mt-auto text-white py-2 px-4 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 text-center block flex items-center justify-center">
            <i class='bx bx-log-out text-2xl mr-2'></i> Salir
        </a>
    </nav>
    <div class="flex-grow">
        {% block content %}
        {% endblock content %}
    </div>

<!-- Cargar la API de Google Maps de forma asíncrona -->
<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYTIrdYoQgrpBfZayR30G6_ObZViJ1Tn4&libraries=places&callback=initAutocomplete"
    async
    defer
></script>
<script>
    let autocomplete;
    function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(
            document.getElementById('location'),
            { types: ['geocode'] }
        );

        autocomplete.addListener('place_changed', function() {
            const place = autocomplete.getPlace();
            document.getElementById('latitude').value = place.geometry.location.lat();
            document.getElementById('longitude').value = place.geometry.location.lng();
        });
    }
</script>
</body>
</html>