config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.user.urls')),
    path('report/', include('core.report.urls')),
    path('messaging/', include('core.messaging.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/messaging/urls.py
from django.urls import path
from .views import send_message, inbox, message_detail

app_name = 'messaging'

urlpatterns = [
    path('send_message/<int:user_id>/', send_message, name='send_message'),
    path('message/<int:sender_id>/', message_detail, name='message_detail'),  # Cambiado a sender_id
    path('inbox/', inbox, name='inbox'),
]

core/report/urls.py
from django.urls import path
from .views import create_report, success_view, edit_report, delete_report, report_list, like_report, add_comment, map_view

app_name = 'report'

urlpatterns = [
    path('', create_report, name='create_report'),
    path('report_list', report_list, name='report_list'),
    path('success/', success_view, name='success'),
    path('edit/<int:report_id>/', edit_report, name='edit_report'),
    path('delete/<int:report_id>/', delete_report, name='delete_report'),
    path('like/<int:report_id>/', like_report, name='like_report'),
    path('comment/<int:report_id>/', add_comment, name='add_comment'),
    path('map/', map_view, name='map'),
]

core/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile_view, name='profile'),
]

core/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El usuario debe tener un correo electrónico')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    city = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
    username = models.CharField(max_length=30, unique=True)
    address = models.CharField(max_length=255)
    profile_image = models.ImageField(upload_to='profileimg/', null=True, blank=True)
    
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    def __str__(self):
        return self.username

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self):
        return self.first_name

core/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from .models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Correo electrónico')
    first_name = forms.CharField(label='Nombre', max_length=30)
    last_name = forms.CharField(label='Apellido', max_length=30)
    city = forms.CharField(label='Ciudad', max_length=50)
    phone_number = forms.CharField(label='Número de teléfono', max_length=15)
    address = forms.CharField(label='Dirección', max_length=255)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'city', 'phone_number', 'username', 'password1', 'password2', 'address']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('first_name'),
            Field('last_name'),
            Field('email'),
            Field('city'),
            Field('phone_number'),
            Field('username'),
            Field('password1'),
            Field('password2'),
            Field('address'),
            Submit('register', 'Registrar')
        )

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label="Nombre de usuario")
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('username'),
            Field('password'),
            Submit('login', 'Iniciar sesión')
        )

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'city', 'phone_number', 'username', 'address', 'profile_image']
        widgets = {
            'profile_image': forms.ClearableFileInput(attrs={'class': 'block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 mt-1'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in ['first_name', 'last_name', 'email', 'city', 'phone_number', 'username', 'address']:
            self.fields[field].disabled = True
        self.fields['profile_image'].required = False

core/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegisterForm, UserLoginForm, UserProfileForm
from core.report.models import Report

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('user:dashboard')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('user:dashboard')
            else:
                form.add_error(None, 'Usuario o contraseña incorrectos.')
    else:
        form = UserLoginForm()

    return render(request, 'login.html', {'form': form})

def user_logout(request):
    logout(request)
    messages.info(request, "Has cerrado sesión exitosamente.")
    return redirect('user:login')

def home_page(request):
    return render(request, 'home.html')

@login_required
def dashboard(request):
    reports = Report.objects.all()
    return render(request, 'dashboard.html', {'reports': reports})

@login_required
def profile_view(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Perfil actualizado exitosamente.')
            return redirect('user:profile')
        else:
            messages.error(request, 'Por favor corrige los errores en el formulario.')
    else:
        form = UserProfileForm(instance=request.user)
    return render(request, 'profile.html', {'form': form})

core/user/templates/dashboard.html
{% extends "sidebar.html" %}
{% load static %}
{% block content %}
<body class="bg-gray-100 flex">
    <div class="flex-1 p-10">
        <section class="text-center py-10 bg-white rounded-lg shadow-md">
            <div class="container mx-auto px-4">
                <h2 class="text-2xl lg:text-3xl text-gray-800 font-bold mb-4">Nuevos reportes de la comunidad</h2>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {% for report in reports %}
                    <div class="bg-white rounded-lg shadow-md p-6 relative">
                        <div class="flex items-center mb-4">
                            {% if report.user.profile_image %}
                                <img src="{{ report.user.profile_image.url }}" alt="Imagen de perfil de {{ report.user.username }}" class="rounded-full h-10 w-10 mr-3">
                            {% else %}
                                <img src="{% static 'img/default_profile.jpg' %}" alt="Imagen de perfil por defecto" class="rounded-full h-10 w-10 mr-3">
                            {% endif %}
                            <span class="text-gray-800 font-bold">{{ report.user.username }}</span>
                        </div>
                        {% if report.media %}
                        <div class="flex justify-center items-center">
                            <img src="{{ report.media.url }}" alt="Report Image" class="rounded-lg shadow-md mb-4 h-60 w-60">
                        </div>
                        {% endif %}
                        <p class="text-gray-800 mb-4">{{ report.pet_description }}</p>
                        <p class="text-gray-800 mb-4">{{ report.post_description }}</p>
                        <div class="flex items-center mb-4">
                            <form action="{% url 'report:like_report' report.id %}" method="post" class="inline-block">
                                {% csrf_token %}
                                <button type="submit" class="text-gray-700 focus:outline-none">
                                    <i class='{% if user in report.likes.all %}bx bxs-heart{% else %}bx bx-heart{% endif %} text-2xl'></i>
                                </button>
                            </form>
                            <span class="ml-2">{{ report.total_likes }}</span>
                            <i class='bx bx-comment text-2xl text-gray-700 ml-6 mr-2'></i> <span>{{ report.comments.count }}</span>
                        </div>
                        <div>
                            {% for comment in report.comments.all %}
                                <div class="bg-gray-100 rounded-lg p-3 mb-2">
                                    <p class="text-gray-800"><strong>{{ comment.user.username }}:</strong> {{ comment.text }}</p>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="mt-4">
                            <form action="{% url 'report:add_comment' report.id %}" method="post">
                                {% csrf_token %}
                                <textarea name="text" rows="2" class="w-full border rounded-md p-2" placeholder="Escribe un comentario..."></textarea>
                                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white py-1 px-4 rounded-md shadow-sm mt-2">Comentar</button>
                            </form>
                        </div>
                        <div class="mt-4">
                            <a href="{% url 'messaging:send_message' report.user.id %}" class="bg-green-500 hover:bg-green-700 text-white py-1 px-4 rounded-md shadow-sm">Enviar mensaje</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
</body>
{% endblock content %}

core/user/templates/login.html
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet Guardian Dashboard</title>

    <!-- Enlaces a estilos -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.1/dist/tailwind.min.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    
</head>
    <div class="bg-gradient-to-b from-blue-500 to-green-500 min-h-screen flex items-center justify-center">
        <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
            <h2 class="text-2xl font-bold mb-6 text-center">Iniciar Sesión</h2>
            <form method="post">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div class="mb-4 text-red-500">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <div class="mb-4">
                    {{ form.username|as_crispy_field }}
                    {% if form.username.errors %}
                        <div class="text-red-500">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span><br>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="mb-4">
                    {{ form.password|as_crispy_field }}
                    {% if form.password.errors %}
                        <div class="text-red-500">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span><br>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <div class="flex justify-center mt-4 space-x-4">
                    <button type="submit" class="w-full bg-blue-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                        Iniciar Sesión
                    </button>
                    <a href="{% url 'user:register' %}" class="w-full bg-green-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 text-center">
                        Registrarse
                    </a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

core/user/templates/profile.html
{% extends "sidebar.html" %}
{% block content %}
<div class="flex items-center justify-center min-h-screen">
    <div class="bg-white rounded-lg shadow-md p-8 max-w-lg w-full">
        <h1 class="text-3xl font-bold mb-6 text-center">Perfil de Usuario</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="mb-4">
                    <label class="block text-gray-700 font-bold" for="id_first_name">Nombre:</label>
                    {{ form.first_name }}
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 font-bold" for="id_last_name">Apellido:</label>
                    {{ form.last_name }}
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 font-bold" for="id_email">Correo Electrónico:</label>
                    {{ form.email }}
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 font-bold" for="id_city">Ciudad:</label>
                    {{ form.city }}
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 font-bold" for="id_phone_number">Número de Teléfono:</label>
                    {{ form.phone_number }}
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 font-bold" for="id_username">Nombre de Usuario:</label>
                    {{ form.username }}
                </div>
                <div class="mb-4 col-span-2">
                    <label class="block text-gray-700 font-bold" for="id_address">Dirección:</label>
                    {{ form.address }}
                </div>
                <div class="mb-4 col-span-2">
                    <label class="block text-gray-700 font-bold" for="id_profile_image">Imagen de Perfil:</label>
                    {% if form.instance.profile_image %}
                        <img src="{{ form.instance.profile_image.url }}" alt="Imagen de Perfil" class="rounded-full h-32 w-32 mx-auto mb-4">
                    {% else %}
                        <p>No hay imagen de perfil disponible.</p>
                    {% endif %}
                    {{ form.profile_image }}
                    {% if form.instance.profile_image %}
                        <p class="text-sm text-gray-500 mt-2">Sube una nueva imagen para actualizar la actual.</p>
                    {% endif %}
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-blue-700 transition duration-300 ease-in-out">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

core/user/templates/register.html
{% load crispy_forms_tags %} {% block content %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pet Guardian Dashboard</title>

    <!-- Enlaces a estilos -->
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.1/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
  </head>
  <div
    class="bg-gradient-to-b from-blue-500 to-green-500 min-h-screen flex items-center justify-center"
  >
    <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-4xl">
      <h2 class="text-2xl font-bold mb-6 text-center">Registrar Usuario</h2>
      <form method="post" class="grid grid-cols-1 md:grid-cols-2 gap-4">
        {% csrf_token %}
        <div class="space-y-4">
          <div>
            <label
              for="first_name"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.first_name|as_crispy_field }}
          </div>
          <div>
            <label
              for="last_name"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.last_name|as_crispy_field }}
          </div>
          <div>
            <label
              for="email"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.email|as_crispy_field }}
          </div>
          <div>
            <label
              for="city"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.city|as_crispy_field }}
          </div>
          <div>
            <label
              for="phone_number"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.phone_number|as_crispy_field }}
          </div>
        </div>
        <!-- Right Column -->
        <div class="space-y-4">
          <div>
            <label
              for="address"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.address|as_crispy_field }}
          </div>
          <div>
            <label
              for="username"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.username|as_crispy_field }}
          </div>
          <div>
            <label
              for="password1"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.password1|as_crispy_field }}
          </div>
          <div>
            <label
              for="password2"
              class="block text-sm font-medium text-gray-700"
            ></label>
            {{ form.password2|as_crispy_field }}
          </div>
        </div>
        <div class="col-span-1 md:col-span-2 text-center">
            <div class="flex justify-center mt-4 space-x-4">
                <button
                    type="submit"
                    class="w-full bg-blue-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                >
                    Register
                </button>
                <a
                    href="{% url 'user:login' %}"
                    class="w-full bg-green-500 text-white py-2 px-4 rounded-md shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 text-center"
                >
                    Login
                </a>
            </div>
        </div>
      </form>
    </div>
  </div>
  {% endblock content %}
</html>